import {pesos,total,totalBruto,cobrado,saldo,fechaHoy} from './core.js';
const ancho=1240,alto=1754;
const fecha=v=>v?new Date(v.slice(0,10)+'T12:00:00Z').toLocaleDateString('es-AR'):'A confirmar';
const fuente=(ctx,n=24,peso=400)=>ctx.font=`${peso} ${n}px Arial`;
function texto(ctx,t,x,y,max,leading=34){const lines=[];for(const parte of String(t||'').split('\n')){let line='';for(const palabra of parte.split(' ')){let chunks=[palabra];if(ctx.measureText(palabra).width>max){chunks=[];let chunk='';for(const ch of palabra){if(ctx.measureText(chunk+ch).width>max){chunks.push(chunk);chunk='';}chunk+=ch;}if(chunk)chunks.push(chunk);}for(const word of chunks){const next=line?(line+' '+word):word;if(ctx.measureText(next).width>max&&line){lines.push(line);line=word;}else line=next;}}lines.push(line);}for(const l of lines){ctx.fillText(l,x,y);y+=leading;}return y;}
function jpeg(ctx){return Uint8Array.from(atob(ctx.canvas.toDataURL('image/jpeg',.95).split(',')[1]),c=>c.charCodeAt(0));}
export function crearPDF(paginas,medidas=[595.28,841.89]){const encoder=new TextEncoder(),chunks=[],offsets=[0];let length=0;const append=t=>{const v=typeof t==='string'?encoder.encode(t):t;chunks.push(v);length+=v.length;};append('%PDF-1.4\n');const obj=(n,content)=>{offsets[n]=length;append(`${n} 0 obj\n`);append(content);append('\nendobj\n');};obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,`<< /Type /Pages /Count ${paginas.length} /Kids [${paginas.map((_,i)=>`${3+i*3} 0 R`).join(' ')}] >>`);paginas.forEach((p,i)=>{const n=3+i*3;obj(n,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${medidas[0]} ${medidas[1]}] /Resources << /XObject << /Im0 ${n+1} 0 R >> >> /Contents ${n+2} 0 R >>`);offsets[n+1]=length;append(`${n+1} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${p.width} /Height ${p.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${p.bytes.length} >>\nstream\n`);append(p.bytes);append('\nendstream\nendobj\n');const stream=`q ${medidas[0]} 0 0 ${medidas[1]} 0 0 cm /Im0 Do Q`;obj(n+2,`<< /Length ${encoder.encode(stream).length} >>\nstream\n${stream}\nendstream`);});const start=length,count=3+paginas.length*3;append(`xref\n0 ${count}\n0000000000 65535 f \n`);for(let i=1;i<count;i++)append(String(offsets[i]).padStart(10,'0')+' 00000 n \n');append(`trailer\n<< /Size ${count} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`);return new Blob(chunks,{type:'application/pdf'});}
export async function descargarDocumento(tipo,p,cliente,config){const logo=await new Promise((res,rej)=>{const img=new Image();img.onload=()=>res(img);img.onerror=()=>rej(Error('No se pudo cargar el logo.'));img.src='./assets/waxi-banner.png';});const pages=[];let ctx,y,pagina=0;
 function nueva(){if(ctx)pages.push({width:ctx.canvas.width,height:ctx.canvas.height,bytes:jpeg(ctx)});const canvas=document.createElement('canvas');canvas.width=ancho;canvas.height=alto;ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,ancho,alto);ctx.drawImage(logo,76,72,360,150);ctx.fillStyle='#26272c';fuente(ctx,38,700);ctx.textAlign='right';ctx.fillText(tipo==='presupuesto'?'PRESUPUESTO':'COMPROBANTE DE PEDIDO',ancho-76,115);fuente(ctx,24);ctx.fillText('#'+p.numero,ancho-76,158);ctx.fillStyle='#666a72';fuente(ctx,21);ctx.fillText('Emitido: '+fecha(fechaHoy()),ancho-76,196);ctx.textAlign='left';ctx.strokeStyle='#e5242c';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(76,248);ctx.lineTo(ancho-76,248);ctx.stroke();ctx.fillStyle='#25272c';fuente(ctx,28,700);y=306;y=texto(ctx,cliente.nombre,76,y,ancho-152,38);fuente(ctx,23);y=texto(ctx,cliente.whatsapp,76,y+5,ancho-152);y=texto(ctx,'Entrega: '+fecha(p.entrega)+' · '+p.formaEntrega,76,y+5,ancho-152);if(p.direccion)y=texto(ctx,p.direccion,76,y+5,ancho-152);y+=40;ctx.fillStyle='#f3f4f6';ctx.fillRect(76,y-30,ancho-152,56);ctx.fillStyle='#555b65';fuente(ctx,20,700);ctx.fillText('PRODUCTO',94,y+5);ctx.fillText('CANT.',730,y+5);ctx.fillText('PRECIO',860,y+5);ctx.textAlign='right';ctx.fillText('SUBTOTAL',ancho-94,y+5);ctx.textAlign='left';y+=82;pagina++;}
 function footer(){ctx.fillStyle='#747883';fuente(ctx,19);ctx.fillText(config.negocio,76,alto-70);ctx.textAlign='right';ctx.fillText('Página '+pagina,ancho-76,alto-70);ctx.textAlign='left';}
 if(tipo==='etiqueta'){const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=600;ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1000,600);ctx.drawImage(logo,40,30,270,112);ctx.fillStyle='#25272c';fuente(ctx,38,700);ctx.textAlign='right';ctx.fillText('PEDIDO #'+p.numero,960,92);ctx.textAlign='left';fuente(ctx,36,700);y=texto(ctx,cliente.nombre,40,200,920,44);fuente(ctx,27);y=texto(ctx,cliente.whatsapp+' · '+p.formaEntrega,40,y+6,920,36);if(p.direccion)y=texto(ctx,p.direccion,40,y+8,920,36);y=texto(ctx,'Entrega: '+fecha(p.entrega),40,y+8,920,36);fuente(ctx,22);const contenido=p.items.map(i=>i.cantidad+' '+i.unidad+'(s) · '+i.nombre).join('\n');texto(ctx,contenido.length>180?contenido.slice(0,177)+'…':contenido,40,y+20,920,28);pages.push({width:1000,height:600,bytes:jpeg(ctx)});return descargar(crearPDF(pages,[283.465,170.079]),'Waxi-etiqueta-'+p.numero+'.pdf');}
 nueva();for(const item of p.items){fuente(ctx,23,600);const words=item.nombre.split(' '),estimate=Math.ceil(ctx.measureText(item.nombre).width/570);const rowH=Math.max(65,estimate*32+22);if(y+rowH>alto-180){footer();nueva();}ctx.fillStyle='#25272c';const end=texto(ctx,item.nombre,94,y,570,32);fuente(ctx,22);ctx.fillText(String(item.cantidad),740,y);ctx.fillText(pesos(item.precio),845,y);ctx.textAlign='right';ctx.fillText(pesos(item.precio*item.cantidad),ancho-94,y);ctx.textAlign='left';y=Math.max(y+rowH,end+18);ctx.strokeStyle='#e3e5e9';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(76,y-15);ctx.lineTo(ancho-76,y-15);ctx.stroke();}
 if(y+240>alto-180){footer();nueva();}y+=30;fuente(ctx,23);ctx.fillStyle='#555b65';ctx.fillText('Subtotal',740,y);ctx.textAlign='right';ctx.fillText(pesos(totalBruto(p)),ancho-94,y);ctx.textAlign='left';y+=42;if(p.descuento){ctx.fillText('Descuento',740,y);ctx.textAlign='right';ctx.fillText('− '+pesos(p.descuento),ancho-94,y);ctx.textAlign='left';y+=42;}ctx.fillStyle='#26272c';fuente(ctx,30,700);ctx.fillText('TOTAL',740,y);ctx.textAlign='right';ctx.fillText(pesos(total(p)),ancho-94,y);ctx.textAlign='left';y+=60;
 if(tipo==='comprobante'){fuente(ctx,23);ctx.fillText('Cobrado: '+pesos(cobrado(p))+'  ·  Saldo: '+pesos(saldo(p)),76,y);y+=44;for(const pago of p.pagos||[]){if(y>alto-160){footer();nueva();}fuente(ctx,20);ctx.fillStyle='#646a75';ctx.fillText(fecha(pago.fecha)+' · '+pago.metodo+' · '+pesos(pago.monto),76,y);y+=30;}}
 const notas=[p.notas,config.notasDocumento,config.contacto,tipo==='comprobante'?'Comprobante interno. No reemplaza una factura fiscal.':''].filter(Boolean).join('\n\n');if(notas){if(y+170>alto-170){footer();nueva();}fuente(ctx,22);ctx.fillStyle='#555b65';const lines=notas.split('\n');for(const line of lines){if(y>alto-190){footer();nueva();}y=texto(ctx,line,76,y+30,ancho-152,30);}}footer();pages.push({width:ancho,height:alto,bytes:jpeg(ctx)});descargar(crearPDF(pages),'Waxi-'+tipo+'-'+p.numero+'.pdf');}
function descargar(blob,nombre){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
