import {configuracionInicial,productosIniciales,fechaHoy} from './core.js';
const req = r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});
const fin = t=>new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error||Error('No se pudo guardar.'));});
let db;
export async function abrir(){const r=indexedDB.open('waxi-app',1);r.onupgradeneeded=()=>{for(const s of ['entidades','meta','copias'])r.result.createObjectStore(s,{keyPath:'id'});};db=await req(r);const c=await obtener('config');if(!c){await guardar({...configuracionInicial(),_seed:true},false);for(const p of productosIniciales())await guardar({...p,tipo:'producto',_seed:true},false);}else if(!c.tipo)await guardar({...c,tipo:'config'},false);await copiaDiaria();}
export async function todas(){return req(db.transaction('entidades').objectStore('entidades').getAll());}
export async function obtener(id){return req(db.transaction('entidades').objectStore('entidades').get(id));}
export async function guardar(e,registrar=true){const viejo=await obtener(e.id);const tx=db.transaction('entidades','readwrite');tx.objectStore('entidades').put({...e,tipo:e.tipo||'config',_seed:registrar?false:(e._seed||false),_version:viejo?._version||0,_pendiente:true,_cambio:crypto.randomUUID(),_actualizado:new Date().toISOString(),_anterior:registrar&&viejo?limpio(viejo):e._anterior});await fin(tx);}
export function limpio(e){const obj={...e};for(const k of Object.keys(obj))if(k.startsWith('_'))delete obj[k];return obj;}
export async function deshacer(id){const e=await obtener(id);if(!e?._anterior)throw Error('No hay un cambio anterior para recuperar.');await guardar(e._anterior);}
export async function meta(id){return req(db.transaction('meta').objectStore('meta').get(id));}
export async function guardarMeta(id,value){const tx=db.transaction('meta','readwrite');tx.objectStore('meta').put({id,value});await fin(tx);}
export async function numeroNuevo(){const tx=db.transaction('meta','readwrite');const s=tx.objectStore('meta');const actual=await req(s.get('numero'));const n=(actual?.value||0)+1;s.put({id:'numero',value:n});await fin(tx);return n;}
export async function copiaDiaria(){const id=fechaHoy();if(await req(db.transaction('copias').objectStore('copias').get(id)))return;const entidades=await todas();const tx=db.transaction('copias','readwrite');tx.objectStore('copias').put({id,entidades});await fin(tx);const copias=await listarCopias();if(copias.length>7){const t=db.transaction('copias','readwrite');for(const e of copias.slice(7))t.objectStore('copias').delete(e.id);await fin(t);}}
export async function listarCopias(){return (await req(db.transaction('copias').objectStore('copias').getAll())).sort((a,b)=>b.id.localeCompare(a.id));}
export async function restaurarCopia(id){const c=await req(db.transaction('copias').objectStore('copias').get(id));if(!c)throw Error('No se encontró la copia.');const actuales=await todas();for(const e of actuales)if(!c.entidades.some(x=>x.id===e.id))await guardar({...e,_oculto:true});for(const e of c.entidades)await guardar(e);}
let sincronizando=false;
export async function sincronizar(){if(sincronizando||!navigator.onLine)return {estado:'offline'};const conn=(await meta('conexion'))?.value;if(!conn)return {estado:'local'};sincronizando=true;try{const local=await todas();const pendientes=local.filter(e=>e._pendiente&&!e._conflicto).slice(0,100);const response=await fetch(conn.url+'/sync',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+conn.clave},body:JSON.stringify({cambios:pendientes.map(e=>({id:e.id,version:e._version,inicial:!!e._seed,operacion:e._cambio,datos:{...limpio(e),_oculto:e._oculto||false}}))})});if(!response.ok)throw Error(response.status===401?'La clave de sincronización no es válida.':'No se pudo sincronizar. Los cambios siguen guardados en este dispositivo.');const data=await response.json();for(const ack of data.aceptados){const e=await obtener(ack.id);if(e){const tx=db.transaction('entidades','readwrite');tx.objectStore('entidades').put({...e,_version:ack.version,_pendiente:e._cambio!==ack.operacion});await fin(tx);}}for(const remoto of data.entidades){const e=await obtener(remoto.id);if(e?._pendiente){if(e._version!==remoto.version){const tx=db.transaction('entidades','readwrite');tx.objectStore('entidades').put({...e,_conflicto:remoto});await fin(tx);}}else{const tx=db.transaction('entidades','readwrite');tx.objectStore('entidades').put({...remoto.datos,id:remoto.id,_version:remoto.version,_pendiente:false});await fin(tx);}}const ns=await todas();const max=Math.max(0,...ns.filter(e=>e.tipo==='pedido').map(e=>e.numero||0));const n=(await meta('numero'))?.value||0;if(max>n)await guardarMeta('numero',max);return {estado:ns.some(e=>e._conflicto)?'conflicto':'ok'};}finally{sincronizando=false;}}
export async function resolverConflicto(id,preferirLocal){const e=await obtener(id);if(!e?._conflicto)return;const remote=e._conflicto;const tx=db.transaction('entidades','readwrite');tx.objectStore('entidades').put(preferirLocal?{...e,_version:remote.version,_conflicto:null,_pendiente:true,_cambio:crypto.randomUUID()}:{...remote.datos,id,_version:remote.version,_pendiente:false});await fin(tx);}
