// Web Push: RFC 8291 (aes128gcm) y RFC 8292 (VAPID), usando Web Crypto.
const enc=new TextEncoder();export const unir=(...xs)=>{const out=new Uint8Array(xs.reduce((n,x)=>n+x.length,0));let off=0;for(const x of xs){out.set(x,off);off+=x.length;}return out;};
export const decodificar=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
export const codificar=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function hmac(key,data){const k=await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,data));}
async function hkdf(key,salt,info,len){const prk=await hmac(salt,key);return (await hmac(prk,unir(info,new Uint8Array([1])))).slice(0,len);}
export async function cifrarPush(subscription,payload){const ua=decodificar(subscription.keys.p256dh),auth=decodificar(subscription.keys.auth);const pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const as=new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey));const user=await crypto.subtle.importKey('raw',ua,{name:'ECDH',namedCurve:'P-256'},false,[]);const shared=new Uint8Array(await crypto.subtle.deriveBits({name:'ECDH',public:user},pair.privateKey,256));const ikm=await hkdf(shared,auth,unir(enc.encode('WebPush: info\0'),ua,as),32);const salt=crypto.getRandomValues(new Uint8Array(16));const cek=await hkdf(ikm,salt,enc.encode('Content-Encoding: aes128gcm\0'),16),nonce=await hkdf(ikm,salt,enc.encode('Content-Encoding: nonce\0'),12);const key=await crypto.subtle.importKey('raw',cek,'AES-GCM',false,['encrypt']);const plain=unir(enc.encode(JSON.stringify(payload)),new Uint8Array([2]));if(plain.length>3993)throw Error('Notificación demasiado larga.');const ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce},key,plain));const rs=new Uint8Array(4);new DataView(rs.buffer).setUint32(0,4096);return unir(salt,rs,new Uint8Array([65]),as,ciphertext);}
export async function enviarPush(subscription,payload,env){const privateKey=await crypto.subtle.importKey('jwk',JSON.parse(env.VAPID_PRIVATE_JWK),{name:'ECDSA',namedCurve:'P-256'},false,['sign']);const endpoint=new URL(subscription.endpoint);const header=codificar(enc.encode(JSON.stringify({typ:'JWT',alg:'ES256'}))),body=codificar(enc.encode(JSON.stringify({aud:endpoint.origin,exp:Math.floor(Date.now()/1000)+43200,sub:env.VAPID_SUBJECT})));const signed=header+'.'+body;const sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},privateKey,enc.encode(signed));return fetch(endpoint.href,{method:'POST',headers:{'Authorization':`vapid t=${signed}.${codificar(sig)}, k=${env.VAPID_PUBLIC_KEY}`,'Content-Encoding':'aes128gcm','Content-Type':'application/octet-stream','TTL':'86400','Urgency':'normal'},body:await cifrarPush(subscription,payload)});}
export function endpointPermitido(value){try{const u=new URL(value);if(u.protocol!=='https:'||u.port||u.username||u.password)return false;return u.hostname==='fcm.googleapis.com'||u.hostname==='web.push.apple.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname.endsWith('.notify.windows.com');}catch{return false;}}
