CREATE TABLE IF NOT EXISTS entidades (id TEXT PRIMARY KEY, version INTEGER NOT NULL, datos TEXT NOT NULL, operacion TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS secuencias (id TEXT PRIMARY KEY, numero INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO secuencias (id,numero) VALUES ('pedidos',0);
CREATE TABLE IF NOT EXISTS suscripciones (endpoint TEXT PRIMARY KEY, datos TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS copias (fecha TEXT PRIMARY KEY, datos TEXT NOT NULL);
