import {enviarPush,endpointPermitido} from './push.js';
import {fechaHoy,sumarDias,indiceEstado,entregado,configuracionInicial} from '../core.js';
function responder(data,status=200,origin=null){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...(origin?{'Access-Control-Allow-Origin':origin,'Vary':'Origin'}:{})}});}
export async function autorizado(req,env){if(!env.ACCESS_KEY||env.ACCESS_KEY.length<32)return false;const token=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';const enc=new TextEncoder();const a=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(token))),b=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(env.ACCESS_KEY)));let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0;}
const rutas=['/sync','/subscription','/push-key','/health'];
function origen(req,env){const origin=req.headers.get('Origin');if(!origin)return null;const allowed=(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);return origin===new URL(req.url).origin||allowed.includes(origin)?origin:false;}
function validarCambio(c){if(!c||typeof c.id!=='string'||c.id.length>100||!Number.isInteger(c.version)||c.version<0||typeof c.operacion!=='string'||!c.datos||c.datos.id!==c.id||!['pedido','cliente','producto','config'].includes(c.datos.tipo))throw Error('Cambio inválido.');if(JSON.stringify(c.datos).length>100000)throw Error('Registro demasiado grande.');}
export default {
 async fetch(req,env){const path=new URL(req.url).pathname;if(!rutas.includes(path))return env.ASSETS?env.ASSETS.fetch(req):responder({error:'No encontrado'},404);const origin=origen(req,env);if(origin===false)return responder({error:'Origen no permitido'},403);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{...(origin?{'Access-Control-Allow-Origin':origin,'Vary':'Origin'}:{}),'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Max-Age':'86400'}});if(!await autorizado(req,env))return responder({error:'Acceso no autorizado'},401,origin);try{
 if(path==='/health'&&req.method==='GET'){await env.DB.prepare('SELECT id FROM entidades LIMIT 1').first();return responder({ok:true,push:!!(env.VAPID_PUBLIC_KEY&&env.VAPID_PRIVATE_JWK&&env.VAPID_SUBJECT)},200,origin);}
 if(path==='/push-key'&&req.method==='GET')return responder({publicKey:env.VAPID_PUBLIC_KEY||null},200,origin);
 if(path==='/subscription'&&req.method==='POST'){const sub=await req.json();if(!endpointPermitido(sub.endpoint)||!sub.keys?.p256dh||!sub.keys?.auth)return responder({error:'Suscripción inválida'},400,origin);if(sub.keys.p256dh.length>100||sub.keys.auth.length>100)return responder({error:'Suscripción inválida'},400,origin);await env.DB.prepare('INSERT INTO suscripciones(endpoint,datos) VALUES(?,?) ON CONFLICT(endpoint) DO UPDATE SET datos=excluded.datos').bind(sub.endpoint,JSON.stringify(sub)).run();return responder({ok:true},200,origin);}
 if(path==='/sync'&&req.method==='POST'){if(Number(req.headers.get('content-length')||0)>1000000)return responder({error:'Solicitud demasiado grande'},413,origin);const text=await req.text();if(text.length>1000000)return responder({error:'Solicitud demasiado grande'},413,origin);const input=JSON.parse(text);if(!Array.isArray(input.cambios)||input.cambios.length>100)return responder({error:'Lote inválido'},400,origin);for(const c of input.cambios)validarCambio(c);const aceptados=[];for(const c of input.cambios){const old=await env.DB.prepare('SELECT version,operacion,datos FROM entidades WHERE id=?').bind(c.id).first();if(old?.operacion===c.operacion||c.inicial&&old){aceptados.push({id:c.id,version:old.version,operacion:c.operacion});continue;}if((old?.version||0)!==c.version)continue;const datos={...c.datos};if(datos.tipo==='pedido'){if(old)datos.numero=JSON.parse(old.datos).numero;else{const serial=await env.DB.prepare("UPDATE secuencias SET numero=numero+1 WHERE id='pedidos' RETURNING numero").first();datos.numero=serial.numero;}}
 const res=await env.DB.prepare('INSERT INTO entidades(id,version,datos,operacion) VALUES(?,1,?,?) ON CONFLICT(id) DO UPDATE SET version=entidades.version+1,datos=excluded.datos,operacion=excluded.operacion WHERE entidades.version=?').bind(c.id,JSON.stringify(datos),c.operacion,c.version).run();if(res.meta.changes){aceptados.push({id:c.id,version:c.version+1,operacion:c.operacion});}}
 const {results}=await env.DB.prepare('SELECT id,version,datos FROM entidades').all();return responder({aceptados,entidades:results.map(r=>({id:r.id,version:r.version,datos:JSON.parse(r.datos)}))},200,origin);}
 return responder({error:'Método no permitido'},405,origin);
 }catch{return responder({error:'No se pudo completar la operación'},500,origin);}},
 async scheduled(event,env,ctx){ctx.waitUntil(recordar(env));}
};
export async function recordar(env){const {results}=await env.DB.prepare('SELECT id,datos FROM entidades').all();const entidades=results.map(r=>JSON.parse(r.datos)),config=entidades.find(e=>e.tipo==='config')||configuracionInicial();const hoy=fechaHoy();await env.DB.prepare('INSERT INTO copias(fecha,datos) VALUES(?,?) ON CONFLICT(fecha) DO UPDATE SET datos=excluded.datos').bind(hoy,JSON.stringify(entidades)).run();await env.DB.prepare('DELETE FROM copias WHERE fecha<?').bind(sumarDias(hoy,-7)).run();if(!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_JWK||!env.VAPID_SUBJECT)return;const pedidos=entidades.filter(p=>p.tipo==='pedido'&&!p._oculto&&!p.anulado&&!p.presupuesto&&!entregado(p,config));const proximos=pedidos.filter(p=>p.entrega&&p.entrega<=sumarDias(hoy,1));const sinAvance=pedidos.filter(p=>!proximos.includes(p)&&p.historial?.length&&Date.now()-new Date(p.historial.at(-1).fecha)>config.diasSinAvance*86400000);const ps=[...proximos.sort((a,b)=>a.entrega.localeCompare(b.entrega)),...sinAvance];if(!ps.length)return;const body=ps.slice(0,4).map(p=>{const nombre=entidades.find(e=>e.id===p.cliente)?.nombre||'Cliente';const cuando=sinAvance.includes(p)?'Sin avance':p.entrega<hoy?'Atrasado':p.entrega===hoy?'Hoy':'Mañana';return `${cuando}: #${p.numero} ${nombre}`;}).join(' · ')+(ps.length>4?` · +${ps.length-4} pedidos`:'');const {results:subs}=await env.DB.prepare('SELECT endpoint,datos FROM suscripciones').all();for(const sub of subs.slice(0,10)){try{const res=await enviarPush(JSON.parse(sub.datos),{title:'Waxi · Entregas y pendientes',body},env);if(res.status===404||res.status===410)await env.DB.prepare('DELETE FROM suscripciones WHERE endpoint=?').bind(sub.endpoint).run();}catch{/* Una suscripción fallida no impide las demás. */}}}
